---
title: "W9_Task_DataSearch"
author: "Daniel Van Gorkum"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
format: html
editor: visual
execute:
  echo: true
  warning: false
  message: false
  keep-md: true
---

```{r}
library(tidyverse)
library(tidyquant)
library(lubridate)
```

```{r}
# Unemployment rate (BLS source, through FRED API)

unemployment <- tq_get("UNRATE", get = "economic.data")

head(unemployment)
unemployment <- unemployment %>%
rename(unemployment_rate = price) %>%
mutate(year = year(date))

```

```{r}
# Check for missing data

unemployment %>%
summarise(missing_values = sum(is.na(unemployment_rate)))

```

```{r}
# Visualize unemployment over time

unemployment %>%
ggplot(aes(x = date, y = unemployment_rate)) +
geom_line(color = "steelblue", linewidth = 1) +
labs(title = "U.S. Unemployment Rate (BLS, 2000–Present)",
x = "Year", y = "Unemployment Rate (%)")

```

```{r}
unemployment %>%
filter(date >= as.Date("2015-01-01")) %>%
ggplot(aes(x = date, y = unemployment_rate)) +
geom_line(color = "darkorange", linewidth = 1) +
geom_point(size = 0.5) +
labs(
title = "U.S. Unemployment Rate (2015–Present)",
subtitle = "Source: BLS via Federal Reserve Economic Data (FRED)",
x = "Date",
y = "Unemployment Rate (%)"
) +
theme_light()

```

```{r}
# Create a decade variable
unemployment <- unemployment %>%
  mutate(decade = floor(year / 10) * 10)

# Boxplot by decade
unemployment %>%
  ggplot(aes(x = factor(decade), y = unemployment_rate, fill = factor(decade))) +
  geom_boxplot(show.legend = FALSE) +
  labs(
    title = "Distribution of Unemployment Rates by Decade",
    x = "Decade",
    y = "Unemployment Rate (%)"
  ) +
  theme_minimal()

```

We can see that during the COVID-19 pandemic that there was great volatility of unemployment with a spike that reached about 15%, but interestingly for the decade the overall mean, median, and upper and lower quartiles were lower than during the 2010s.
